default:
  module: "src.client.agents.FastChatAgent"
  parameters:
    name: "FastChat"
    controller_address: "https://iv25t5kp7tzwju-8800.proxy.runpod.net"
    max_new_tokens: 1024
    temperature: 0

db_orig_db_manual_reviewed:
  parameters:
    model_name: "YieldInc/db_orig_db_manual_reviewed"
