import: definition.yaml

concurrency:
  task:
    alfworld-dev: 3
  agent:
    gpt-4-1106-preview: 1

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      - gpt-4-1106-preview
    task:
      - alfworld-dev

output: "outputs/{TIMESTAMP}"
