import: definition.yaml

concurrency:
  task:
    os-dev: 1
    dbbench-dev: 1
  agent:
    db_orig_db_manual_reviewed: 1

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      - db_orig_db_manual_reviewed
    task:
      - os-dev
      - dbbench-dev

output: "outputs/{TIMESTAMP}"
